import { ENV } from './env';

interface EmailOptions {
  to: string;
  subject: string;
  html: string;
}

/**
 * Send email using a production email service
 * In production, integrate with SendGrid, AWS SES, or similar
 */
export async function sendEmail(options: EmailOptions): Promise<boolean> {
  try {
    // For now, log to console
    // In production, replace with actual email service API call
    console.log(`[EMAIL] To: ${options.to}`);
    console.log(`[EMAIL] Subject: ${options.subject}`);
    console.log(`[EMAIL] Body: ${options.html.substring(0, 200)}...`);
    
    // Simulate email sending
    // In production:
    // const response = await fetch('https://api.sendgrid.com/v3/mail/send', {
    //   method: 'POST',
    //   headers: {
    //     'Authorization': `Bearer ${process.env.SENDGRID_API_KEY}`,
    //     'Content-Type': 'application/json',
    //   },
    //   body: JSON.stringify({
    //     personalizations: [{ to: [{ email: options.to }] }],
    //     from: { email: 'noreply@azvirt.com' },
    //     subject: options.subject,
    //     content: [{ type: 'text/html', value: options.html }],
    //   }),
    // });
    
    return true;
  } catch (error) {
    console.error('[EMAIL] Failed to send:', error);
    return false;
  }
}

/**
 * Generate low stock alert email HTML
 */
export function generateLowStockEmailHTML(materials: Array<{
  name: string;
  quantity: number;
  unit: string;
  criticalThreshold: number;
  supplier?: string;
  supplierEmail?: string;
}>): string {
  const materialRows = materials.map(m => `
    <tr>
      <td style="padding: 12px; border-bottom: 1px solid #e5e7eb;">${m.name}</td>
      <td style="padding: 12px; border-bottom: 1px solid #e5e7eb; color: #dc2626; font-weight: bold;">${m.quantity} ${m.unit}</td>
      <td style="padding: 12px; border-bottom: 1px solid #e5e7eb;">${m.criticalThreshold} ${m.unit}</td>
      <td style="padding: 12px; border-bottom: 1px solid #e5e7eb;">${m.supplier || 'N/A'}</td>
    </tr>
  `).join('');

  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Low Stock Alert - AzVirt DMS</title>
</head>
<body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; padding: 20px;">
  <div style="background: linear-gradient(135deg, #f97316 0%, #ea580c 100%); padding: 30px; text-align: center; border-radius: 8px 8px 0 0;">
    <h1 style="color: white; margin: 0; font-size: 24px;">⚠️ Low Stock Alert</h1>
    <p style="color: rgba(255,255,255,0.9); margin: 10px 0 0 0;">AzVirt Document Management System</p>
  </div>
  
  <div style="background: #ffffff; padding: 30px; border: 1px solid #e5e7eb; border-top: none; border-radius: 0 0 8px 8px;">
    <p style="font-size: 16px; margin-bottom: 20px;">
      <strong>Upozorenje:</strong> Sljedeći materijali su ispod kritičnog nivoa zaliha i zahtijevaju hitnu narudžbu.
    </p>
    
    <p style="font-size: 16px; margin-bottom: 20px;">
      <strong>Warning:</strong> The following materials are below critical stock levels and require urgent ordering.
    </p>
    
    <table style="width: 100%; border-collapse: collapse; margin: 20px 0;">
      <thead>
        <tr style="background-color: #f3f4f6;">
          <th style="padding: 12px; text-align: left; border-bottom: 2px solid #e5e7eb;">Material / Materijal</th>
          <th style="padding: 12px; text-align: left; border-bottom: 2px solid #e5e7eb;">Current / Trenutno</th>
          <th style="padding: 12px; text-align: left; border-bottom: 2px solid #e5e7eb;">Threshold / Prag</th>
          <th style="padding: 12px; text-align: left; border-bottom: 2px solid #e5e7eb;">Supplier / Dobavljač</th>
        </tr>
      </thead>
      <tbody>
        ${materialRows}
      </tbody>
    </table>
    
    <div style="background: #fef3c7; border-left: 4px solid #f59e0b; padding: 15px; margin: 20px 0; border-radius: 4px;">
      <p style="margin: 0; font-size: 14px;">
        <strong>Preporučena akcija / Recommended Action:</strong><br>
        Kreirajte narudžbenicu odmah kako biste izbjegli zastoje u proizvodnji.<br>
        Create purchase orders immediately to avoid production delays.
      </p>
    </div>
    
    <p style="font-size: 14px; color: #6b7280; margin-top: 30px;">
      Ova automatska poruka je generisana od strane AzVirt DMS sistema.<br>
      This is an automated message generated by AzVirt DMS.
    </p>
  </div>
</body>
</html>
  `;
}

/**
 * Generate purchase order email HTML
 */
export function generatePurchaseOrderEmailHTML(order: {
  id: number;
  materialName: string;
  quantity: number;
  supplier: string;
  expectedDelivery?: Date;
  notes?: string;
}): string {
  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Purchase Order - AzVirt DMS</title>
</head>
<body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; padding: 20px;">
  <div style="background: linear-gradient(135deg, #f97316 0%, #ea580c 100%); padding: 30px; text-align: center; border-radius: 8px 8px 0 0;">
    <h1 style="color: white; margin: 0; font-size: 24px;">📦 Purchase Order</h1>
    <p style="color: rgba(255,255,255,0.9); margin: 10px 0 0 0;">Narudžbenica / Order #${order.id}</p>
  </div>
  
  <div style="background: #ffffff; padding: 30px; border: 1px solid #e5e7eb; border-top: none; border-radius: 0 0 8px 8px;">
    <p style="font-size: 16px; margin-bottom: 20px;">
      Poštovani <strong>${order.supplier}</strong>,
    </p>
    
    <p style="font-size: 16px; margin-bottom: 20px;">
      Molimo vas da obradite sljedeću narudžbu:<br>
      Please process the following order:
    </p>
    
    <div style="background: #f9fafb; padding: 20px; border-radius: 8px; margin: 20px 0;">
      <table style="width: 100%;">
        <tr>
          <td style="padding: 8px 0;"><strong>Material / Materijal:</strong></td>
          <td style="padding: 8px 0;">${order.materialName}</td>
        </tr>
        <tr>
          <td style="padding: 8px 0;"><strong>Quantity / Količina:</strong></td>
          <td style="padding: 8px 0; font-size: 18px; color: #f97316; font-weight: bold;">${order.quantity}</td>
        </tr>
        ${order.expectedDelivery ? `
        <tr>
          <td style="padding: 8px 0;"><strong>Expected Delivery / Očekivana isporuka:</strong></td>
          <td style="padding: 8px 0;">${new Date(order.expectedDelivery).toLocaleDateString()}</td>
        </tr>
        ` : ''}
        ${order.notes ? `
        <tr>
          <td style="padding: 8px 0; vertical-align: top;"><strong>Notes / Napomene:</strong></td>
          <td style="padding: 8px 0;">${order.notes}</td>
        </tr>
        ` : ''}
      </table>
    </div>
    
    <p style="font-size: 16px; margin-top: 20px;">
      Molimo vas da potvrdite prijem ove narudžbe i datum isporuke.<br>
      Please confirm receipt of this order and delivery date.
    </p>
    
    <p style="font-size: 14px; color: #6b7280; margin-top: 30px; padding-top: 20px; border-top: 1px solid #e5e7eb;">
      S poštovanjem / Best regards,<br>
      <strong>AzVirt Team</strong><br>
      <a href="mailto:info@azvirt.com" style="color: #f97316;">info@azvirt.com</a>
    </p>
  </div>
</body>
</html>
  `;
}

/**
 * Generate daily production report email HTML
 */
export function generateDailyProductionReportHTML(report: {
  date: string;
  totalConcreteProduced: number;
  deliveriesCompleted: number;
  materialConsumption: Array<{ name: string; quantity: number; unit: string }>;
  qualityTests: { total: number; passed: number; failed: number };
}): string {
  const materialRows = report.materialConsumption.map(m => `
    <tr>
      <td style="padding: 8px; border-bottom: 1px solid #e5e7eb;">${m.name}</td>
      <td style="padding: 8px; border-bottom: 1px solid #e5e7eb; text-align: right; font-weight: bold;">${m.quantity} ${m.unit}</td>
    </tr>
  `).join('');

  const passRate = report.qualityTests.total > 0 
    ? ((report.qualityTests.passed / report.qualityTests.total) * 100).toFixed(1)
    : '0';

  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Daily Production Report - AzVirt DMS</title>
</head>
<body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 700px; margin: 0 auto; padding: 20px;">
  <div style="background: linear-gradient(135deg, #f97316 0%, #ea580c 100%); padding: 30px; text-align: center; border-radius: 8px 8px 0 0;">
    <h1 style="color: white; margin: 0; font-size: 28px;">📊 Daily Production Report</h1>
    <p style="color: rgba(255,255,255,0.9); margin: 10px 0 0 0; font-size: 18px;">${report.date}</p>
  </div>
  
  <div style="background: #ffffff; padding: 30px; border: 1px solid #e5e7eb; border-top: none; border-radius: 0 0 8px 8px;">
    
    <!-- Key Metrics -->
    <div style="display: grid; grid-template-columns: repeat(3, 1fr); gap: 15px; margin-bottom: 30px;">
      <div style="background: #fef3c7; padding: 20px; border-radius: 8px; text-align: center;">
        <div style="font-size: 32px; font-weight: bold; color: #f97316;">${report.totalConcreteProduced}</div>
        <div style="font-size: 14px; color: #78350f; margin-top: 5px;">m³ Concrete<br>Betona</div>
      </div>
      <div style="background: #dbeafe; padding: 20px; border-radius: 8px; text-align: center;">
        <div style="font-size: 32px; font-weight: bold; color: #2563eb;">${report.deliveriesCompleted}</div>
        <div style="font-size: 14px; color: #1e3a8a; margin-top: 5px;">Deliveries<br>Isporuka</div>
      </div>
      <div style="background: #dcfce7; padding: 20px; border-radius: 8px; text-align: center;">
        <div style="font-size: 32px; font-weight: bold; color: #16a34a;">${passRate}%</div>
        <div style="font-size: 14px; color: #14532d; margin-top: 5px;">QC Pass Rate<br>Prolaznost</div>
      </div>
    </div>
    
    <!-- Material Consumption -->
    <h2 style="color: #111827; font-size: 20px; margin-top: 30px; margin-bottom: 15px; border-bottom: 2px solid #f97316; padding-bottom: 10px;">
      Material Consumption / Potrošnja materijala
    </h2>
    <table style="width: 100%; border-collapse: collapse;">
      <thead>
        <tr style="background-color: #f3f4f6;">
          <th style="padding: 12px; text-align: left; border-bottom: 2px solid #e5e7eb;">Material</th>
          <th style="padding: 12px; text-align: right; border-bottom: 2px solid #e5e7eb;">Quantity</th>
        </tr>
      </thead>
      <tbody>
        ${materialRows}
      </tbody>
    </table>
    
    <!-- Quality Control Summary -->
    <h2 style="color: #111827; font-size: 20px; margin-top: 30px; margin-bottom: 15px; border-bottom: 2px solid #f97316; padding-bottom: 10px;">
      Quality Control / Kontrola kvaliteta
    </h2>
    <div style="background: #f9fafb; padding: 20px; border-radius: 8px;">
      <div style="display: flex; justify-content: space-between; margin-bottom: 10px;">
        <span>Total Tests / Ukupno testova:</span>
        <strong>${report.qualityTests.total}</strong>
      </div>
      <div style="display: flex; justify-content: space-between; margin-bottom: 10px;">
        <span style="color: #16a34a;">✓ Passed / Prošlo:</span>
        <strong style="color: #16a34a;">${report.qualityTests.passed}</strong>
      </div>
      <div style="display: flex; justify-content: space-between;">
        <span style="color: #dc2626;">✗ Failed / Palo:</span>
        <strong style="color: #dc2626;">${report.qualityTests.failed}</strong>
      </div>
    </div>
    
    <p style="font-size: 14px; color: #6b7280; margin-top: 30px; padding-top: 20px; border-top: 1px solid #e5e7eb;">
      This automated report is generated daily by AzVirt DMS.<br>
      Ovaj automatski izvještaj se generiše dnevno od strane AzVirt DMS sistema.
    </p>
  </div>
</body>
</html>
  `;
}
