import * as db from "../db";

// Template types supported by the system
export type EmailTemplateType =
  | "daily_production_report"
  | "low_stock_alert"
  | "purchase_order"
  | "generic_notification";

// Branding settings interface
export interface BrandingSettings {
  logoUrl: string | null;
  primaryColor: string;
  secondaryColor: string;
  companyName: string;
  footerText: string | null;
  headerStyle: "gradient" | "solid" | "minimal";
  fontFamily: string;
}

// Template variables interface
export interface TemplateVariables {
  [key: string]: string | number | boolean | null | undefined;
}

// Default branding settings
const DEFAULT_BRANDING: BrandingSettings = {
  logoUrl: null,
  primaryColor: "#f97316",
  secondaryColor: "#ea580c",
  companyName: "AzVirt",
  footerText: null,
  headerStyle: "gradient",
  fontFamily: "Arial, sans-serif",
};

// Available variables for each template type
export const TEMPLATE_VARIABLES: Record<EmailTemplateType, string[]> = {
  daily_production_report: [
    "{{date}}",
    "{{totalConcreteProduced}}",
    "{{deliveriesCompleted}}",
    "{{qualityTestsTotal}}",
    "{{qualityTestsPassed}}",
    "{{qualityTestsFailed}}",
    "{{passRate}}",
    "{{materialRows}}",
    "{{metricsHtml}}",
    "{{qualityHtml}}",
  ],
  low_stock_alert: [
    "{{materialCount}}",
    "{{materialRows}}",
    "{{urgentCount}}",
    "{{warningCount}}",
  ],
  purchase_order: [
    "{{orderId}}",
    "{{materialName}}",
    "{{quantity}}",
    "{{unit}}",
    "{{supplier}}",
    "{{orderDate}}",
    "{{expectedDelivery}}",
    "{{notes}}",
    "{{totalCost}}",
  ],
  generic_notification: [
    "{{title}}",
    "{{message}}",
    "{{actionUrl}}",
    "{{actionText}}",
    "{{timestamp}}",
  ],
};

/**
 * Get branding settings from database or return defaults
 */
export async function getBrandingSettings(): Promise<BrandingSettings> {
  const branding = await db.getEmailBranding();
  if (!branding) {
    return DEFAULT_BRANDING;
  }
  return {
    logoUrl: branding.logoUrl,
    primaryColor: branding.primaryColor,
    secondaryColor: branding.secondaryColor,
    companyName: branding.companyName,
    footerText: branding.footerText,
    headerStyle: (branding.headerStyle as BrandingSettings["headerStyle"]) || "gradient",
    fontFamily: branding.fontFamily,
  };
}

/**
 * Generate the email header HTML based on branding settings
 */
function generateHeader(
  branding: BrandingSettings,
  title: string,
  subtitle?: string
): string {
  const { logoUrl, primaryColor, secondaryColor, companyName, headerStyle, fontFamily } =
    branding;

  let backgroundStyle = "";
  switch (headerStyle) {
    case "gradient":
      backgroundStyle = `background: linear-gradient(135deg, ${primaryColor} 0%, ${secondaryColor} 100%);`;
      break;
    case "solid":
      backgroundStyle = `background-color: ${primaryColor};`;
      break;
    case "minimal":
      backgroundStyle = `background-color: #ffffff; border-bottom: 4px solid ${primaryColor};`;
      break;
  }

  const textColor = headerStyle === "minimal" ? primaryColor : "white";

  const logoHtml = logoUrl
    ? `<img src="${logoUrl}" alt="${companyName}" style="max-height: 50px; width: auto; margin-right: 15px; ${headerStyle === "minimal" ? "" : "filter: brightness(0) invert(1);"}"/>`
    : "";

  return `
    <div style="${backgroundStyle} padding: 30px; text-align: center; border-radius: 8px 8px 0 0; font-family: ${fontFamily};">
      <div style="display: flex; align-items: center; justify-content: center; gap: 15px;">
        ${logoHtml}
        <div>
          <h1 style="color: ${textColor}; margin: 0; font-size: 28px;">${title}</h1>
          ${subtitle ? `<p style="color: ${headerStyle === "minimal" ? "#666" : "rgba(255,255,255,0.9)"}; margin: 10px 0 0 0; font-size: 16px;">${subtitle}</p>` : ""}
        </div>
      </div>
    </div>
  `;
}

/**
 * Generate the email footer HTML based on branding settings
 */
function generateFooter(branding: BrandingSettings): string {
  const { primaryColor, companyName, footerText, fontFamily } = branding;

  const defaultFooter = `This automated message is generated by ${companyName} DMS.`;
  const footer = footerText || defaultFooter;

  return `
    <div style="background-color: ${primaryColor}10; padding: 20px; text-align: center; border-top: 1px solid #e5e7eb; font-family: ${fontFamily};">
      <p style="font-size: 12px; color: #6b7280; margin: 0;">${footer}</p>
      <p style="font-size: 11px; color: #9ca3af; margin: 10px 0 0 0;">© ${new Date().getFullYear()} ${companyName}. All rights reserved.</p>
    </div>
  `;
}

/**
 * Wrap content with email base template
 */
function wrapWithBaseTemplate(
  branding: BrandingSettings,
  header: string,
  content: string,
  footer: string
): string {
  const { fontFamily } = branding;

  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Email from ${branding.companyName}</title>
</head>
<body style="font-family: ${fontFamily}; line-height: 1.6; color: #333; max-width: 700px; margin: 0 auto; padding: 20px; background-color: #f5f5f5;">
  <div style="background: #ffffff; border-radius: 8px; overflow: hidden; box-shadow: 0 2px 10px rgba(0,0,0,0.1);">
    ${header}
    <div style="padding: 30px;">
      ${content}
    </div>
    ${footer}
  </div>
</body>
</html>
  `;
}

/**
 * Replace template variables with actual values
 */
function replaceVariables(template: string, variables: TemplateVariables): string {
  let result = template;
  for (const [key, value] of Object.entries(variables)) {
    const regex = new RegExp(`{{${key}}}`, "g");
    result = result.replace(regex, value?.toString() ?? "");
  }
  return result;
}

/**
 * Get default template content for a template type
 */
export function getDefaultTemplateContent(type: EmailTemplateType): {
  name: string;
  subject: string;
  bodyHtml: string;
  description: string;
} {
  switch (type) {
    case "daily_production_report":
      return {
        name: "Daily Production Report",
        description: "Sent daily with production metrics, deliveries, and quality control data",
        subject: "📊 Daily Production Report - {{date}}",
        bodyHtml: `
          <div style="display: grid; grid-template-columns: repeat(auto-fit, minmax(150px, 1fr)); gap: 15px; margin-bottom: 30px;">
            {{metricsHtml}}
          </div>

          <h2 style="color: #111827; font-size: 20px; margin-top: 30px; margin-bottom: 15px; border-bottom: 2px solid {{primaryColor}}; padding-bottom: 10px;">
            Material Consumption / Potrošnja materijala
          </h2>
          <table style="width: 100%; border-collapse: collapse;">
            <thead>
              <tr style="background-color: #f3f4f6;">
                <th style="padding: 12px; text-align: left; border-bottom: 2px solid #e5e7eb;">Material</th>
                <th style="padding: 12px; text-align: right; border-bottom: 2px solid #e5e7eb;">Quantity</th>
              </tr>
            </thead>
            <tbody>
              {{materialRows}}
            </tbody>
          </table>

          {{qualityHtml}}
        `,
      };

    case "low_stock_alert":
      return {
        name: "Low Stock Alert",
        description: "Sent when materials fall below minimum stock levels",
        subject: "⚠️ Low Stock Alert - {{materialCount}} materials need attention",
        bodyHtml: `
          <p style="font-size: 16px; margin-bottom: 20px;">
            The following materials are running low and need to be reordered:<br>
            <em>Sljedeći materijali su pri kraju i potrebno ih je naručiti:</em>
          </p>

          <table style="width: 100%; border-collapse: collapse; margin-top: 20px;">
            <thead>
              <tr style="background-color: #f3f4f6;">
                <th style="padding: 12px; text-align: left; border-bottom: 2px solid #e5e7eb;">Material / Materijal</th>
                <th style="padding: 12px; text-align: center; border-bottom: 2px solid #e5e7eb;">Current Stock / Trenutna zaliha</th>
                <th style="padding: 12px; text-align: center; border-bottom: 2px solid #e5e7eb;">Reorder Level / Nivo narudžbe</th>
              </tr>
            </thead>
            <tbody>
              {{materialRows}}
            </tbody>
          </table>

          <div style="margin-top: 30px; padding: 20px; background-color: #fef2f2; border-left: 4px solid #dc2626; border-radius: 4px;">
            <p style="margin: 0; font-weight: bold; color: #991b1b;">Action Required / Potrebna akcija:</p>
            <p style="margin: 10px 0 0 0; color: #7f1d1d;">
              Please create purchase orders for these materials to avoid production delays.<br>
              <em>Molimo kreirajte narudžbenice za ove materijale kako biste izbjegli kašnjenja u proizvodnji.</em>
            </p>
          </div>
        `,
      };

    case "purchase_order":
      return {
        name: "Purchase Order",
        description: "Sent to suppliers when creating new purchase orders",
        subject: "📦 Purchase Order #{{orderId}} - {{companyName}}",
        bodyHtml: `
          <p style="font-size: 16px; margin-bottom: 20px;">
            Dear {{supplier}},<br>
            <em>Poštovani {{supplier}},</em>
          </p>

          <p>
            We would like to place the following order:<br>
            <em>Želimo da naručimo sljedeće:</em>
          </p>

          <div style="background: #f9fafb; padding: 20px; border-radius: 8px; margin: 20px 0;">
            <table style="width: 100%;">
              <tr>
                <td style="padding: 8px 0; font-weight: bold;">Material / Materijal:</td>
                <td style="padding: 8px 0; text-align: right;">{{materialName}}</td>
              </tr>
              <tr>
                <td style="padding: 8px 0; font-weight: bold;">Quantity / Količina:</td>
                <td style="padding: 8px 0; text-align: right; font-size: 20px; color: {{primaryColor}};">{{quantity}} {{unit}}</td>
              </tr>
              <tr>
                <td style="padding: 8px 0; font-weight: bold;">Order Date / Datum narudžbe:</td>
                <td style="padding: 8px 0; text-align: right;">{{orderDate}}</td>
              </tr>
              <tr>
                <td style="padding: 8px 0; font-weight: bold;">Expected Delivery / Očekivana isporuka:</td>
                <td style="padding: 8px 0; text-align: right;">{{expectedDelivery}}</td>
              </tr>
            </table>
          </div>

          <div style="margin: 20px 0;">
            <p style="font-weight: bold; margin-bottom: 10px;">Additional Notes / Dodatne napomene:</p>
            <p style="background: #fef3c7; padding: 15px; border-radius: 4px; margin: 0;">{{notes}}</p>
          </div>

          <p style="margin-top: 30px;">
            Please confirm receipt of this order and provide delivery timeline.<br>
            <em>Molimo potvrdite prijem ove narudžbe i dostavite rok isporuke.</em>
          </p>

          <p style="margin-top: 20px;">
            Best regards,<br>
            <strong>{{companyName}} Team</strong>
          </p>
        `,
      };

    case "generic_notification":
      return {
        name: "Generic Notification",
        description: "General purpose notification template",
        subject: "{{title}} - {{companyName}}",
        bodyHtml: `
          <h2 style="color: #111827; font-size: 24px; margin-bottom: 20px;">{{title}}</h2>

          <div style="font-size: 16px; line-height: 1.8;">
            {{message}}
          </div>

          <div style="margin-top: 30px; text-align: center;">
            <a href="{{actionUrl}}" style="display: inline-block; background-color: {{primaryColor}}; color: white; padding: 12px 30px; text-decoration: none; border-radius: 6px; font-weight: bold;">
              {{actionText}}
            </a>
          </div>

          <p style="font-size: 12px; color: #6b7280; margin-top: 30px; text-align: center;">
            Sent at: {{timestamp}}
          </p>
        `,
      };
  }
}

/**
 * Generate an email using a template type with branding
 */
export async function generateEmailFromTemplate(
  type: EmailTemplateType,
  variables: TemplateVariables,
  options?: {
    headerTitle?: string;
    headerSubtitle?: string;
  }
): Promise<{ subject: string; html: string }> {
  // Get branding settings
  const branding = await getBrandingSettings();

  // Get custom template from database or use default
  const customTemplate = await db.getEmailTemplateByType(type);
  const defaultTemplate = getDefaultTemplateContent(type);

  // Use custom template if it exists and is active, otherwise use default
  const template =
    customTemplate && customTemplate.isActive && customTemplate.isCustom
      ? {
          subject: customTemplate.subject,
          bodyHtml: customTemplate.bodyHtml,
          name: customTemplate.name,
        }
      : defaultTemplate;

  // Add branding variables
  const allVariables: TemplateVariables = {
    ...variables,
    primaryColor: branding.primaryColor,
    secondaryColor: branding.secondaryColor,
    companyName: branding.companyName,
  };

  // Replace variables in subject and body
  const subject = replaceVariables(template.subject, allVariables);
  const bodyContent = replaceVariables(template.bodyHtml, allVariables);

  // Generate header and footer
  const headerTitle = options?.headerTitle || template.name;
  const headerSubtitle = options?.headerSubtitle;
  const header = generateHeader(branding, headerTitle, headerSubtitle);
  const footer = generateFooter(branding);

  // Wrap everything together
  const html = wrapWithBaseTemplate(branding, header, bodyContent, footer);

  return { subject, html };
}

/**
 * Generate a preview of an email with sample data
 */
export async function generateEmailPreview(
  type: EmailTemplateType,
  customSubject?: string,
  customBodyHtml?: string
): Promise<{ subject: string; html: string }> {
  const branding = await getBrandingSettings();

  // Sample data for preview
  const sampleData: Record<EmailTemplateType, TemplateVariables> = {
    daily_production_report: {
      date: new Date().toLocaleDateString(),
      totalConcreteProduced: 250,
      deliveriesCompleted: 12,
      qualityTestsTotal: 15,
      qualityTestsPassed: 14,
      qualityTestsFailed: 1,
      passRate: "93.3",
      materialRows: `
        <tr><td style="padding: 8px; border-bottom: 1px solid #e5e7eb;">Cement Portland</td><td style="padding: 8px; border-bottom: 1px solid #e5e7eb; text-align: right; font-weight: bold;">45 tons</td></tr>
        <tr><td style="padding: 8px; border-bottom: 1px solid #e5e7eb;">Sand</td><td style="padding: 8px; border-bottom: 1px solid #e5e7eb; text-align: right; font-weight: bold;">120 m³</td></tr>
        <tr><td style="padding: 8px; border-bottom: 1px solid #e5e7eb;">Gravel</td><td style="padding: 8px; border-bottom: 1px solid #e5e7eb; text-align: right; font-weight: bold;">85 m³</td></tr>
      `,
      metricsHtml: `
        <div style="background: #fef3c7; padding: 20px; border-radius: 8px; text-align: center;">
          <div style="font-size: 32px; font-weight: bold; color: ${branding.primaryColor};">250</div>
          <div style="font-size: 14px; color: #78350f; margin-top: 5px;">m³ Concrete</div>
        </div>
        <div style="background: #dbeafe; padding: 20px; border-radius: 8px; text-align: center;">
          <div style="font-size: 32px; font-weight: bold; color: #2563eb;">12</div>
          <div style="font-size: 14px; color: #1e3a8a; margin-top: 5px;">Deliveries</div>
        </div>
        <div style="background: #dcfce7; padding: 20px; border-radius: 8px; text-align: center;">
          <div style="font-size: 32px; font-weight: bold; color: #16a34a;">93.3%</div>
          <div style="font-size: 14px; color: #14532d; margin-top: 5px;">QC Pass Rate</div>
        </div>
      `,
      qualityHtml: `
        <h2 style="color: #111827; font-size: 20px; margin-top: 30px; margin-bottom: 15px; border-bottom: 2px solid ${branding.primaryColor}; padding-bottom: 10px;">Quality Control</h2>
        <div style="background: #f9fafb; padding: 20px; border-radius: 8px;">
          <div style="display: flex; justify-content: space-between; margin-bottom: 10px;"><span>Total Tests:</span><strong>15</strong></div>
          <div style="display: flex; justify-content: space-between; margin-bottom: 10px;"><span style="color: #16a34a;">✓ Passed:</span><strong style="color: #16a34a;">14</strong></div>
          <div style="display: flex; justify-content: space-between;"><span style="color: #dc2626;">✗ Failed:</span><strong style="color: #dc2626;">1</strong></div>
        </div>
      `,
    },
    low_stock_alert: {
      materialCount: 3,
      urgentCount: 1,
      warningCount: 2,
      materialRows: `
        <tr>
          <td style="padding: 12px; border-bottom: 1px solid #e5e7eb;">Cement Portland</td>
          <td style="padding: 12px; border-bottom: 1px solid #e5e7eb; text-align: center;"><span style="color: #dc2626; font-weight: bold;">15 tons</span></td>
          <td style="padding: 12px; border-bottom: 1px solid #e5e7eb; text-align: center;">50 tons</td>
        </tr>
        <tr>
          <td style="padding: 12px; border-bottom: 1px solid #e5e7eb;">Admixture A</td>
          <td style="padding: 12px; border-bottom: 1px solid #e5e7eb; text-align: center;"><span style="color: #f59e0b; font-weight: bold;">25 L</span></td>
          <td style="padding: 12px; border-bottom: 1px solid #e5e7eb; text-align: center;">30 L</td>
        </tr>
      `,
    },
    purchase_order: {
      orderId: 1234,
      materialName: "Portland Cement Type I",
      quantity: 100,
      unit: "tons",
      supplier: "Holcim d.o.o.",
      orderDate: new Date().toLocaleDateString(),
      expectedDelivery: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toLocaleDateString(),
      notes: "Please deliver to main warehouse gate. Contact +387 61 123 456 upon arrival.",
      totalCost: "12,500.00 KM",
    },
    generic_notification: {
      title: "System Update Notification",
      message: "A new update has been deployed to the AzVirt DMS system. Please review the changelog for details about new features and improvements.",
      actionUrl: "https://app.azvirt.com/changelog",
      actionText: "View Changelog",
      timestamp: new Date().toLocaleString(),
    },
  };

  const defaultTemplate = getDefaultTemplateContent(type);
  const variables = {
    ...sampleData[type],
    primaryColor: branding.primaryColor,
    secondaryColor: branding.secondaryColor,
    companyName: branding.companyName,
  };

  const subject = replaceVariables(customSubject || defaultTemplate.subject, variables);
  const bodyContent = replaceVariables(customBodyHtml || defaultTemplate.bodyHtml, variables);

  const header = generateHeader(branding, defaultTemplate.name);
  const footer = generateFooter(branding);

  const html = wrapWithBaseTemplate(branding, header, bodyContent, footer);

  return { subject, html };
}

/**
 * Initialize default templates in database
 */
export async function initializeDefaultTemplates(): Promise<void> {
  const templateTypes: EmailTemplateType[] = [
    "daily_production_report",
    "low_stock_alert",
    "purchase_order",
    "generic_notification",
  ];

  for (const type of templateTypes) {
    const existing = await db.getEmailTemplateByType(type);
    if (!existing) {
      const defaultContent = getDefaultTemplateContent(type);
      await db.upsertEmailTemplate({
        type,
        name: defaultContent.name,
        description: defaultContent.description,
        subject: defaultContent.subject,
        bodyHtml: defaultContent.bodyHtml,
        isCustom: false,
        isActive: true,
        variables: TEMPLATE_VARIABLES[type],
      });
      console.log(`[EmailTemplates] Initialized default template: ${type}`);
    }
  }
}
